<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Operations | BloomKeeper</title>
    @if (file_exists(public_path('build/manifest.json')) || file_exists(public_path('hot')))
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    @endif
</head>
<body class="min-h-screen bg-[#c4e6e1] font-sans text-[#203d37]">
<div class="mx-auto flex min-h-screen max-w-[1500px] gap-6 p-4 sm:p-6">
    <x-admin.sidebar />
    <main class="min-w-0 flex-1 py-2 lg:py-4">
    <header class="flex flex-wrap items-end justify-between gap-4">
        <div><a href="{{ route('admin.dashboard') }}" class="text-sm font-semibold underline">Back to overview</a><h1 class="mt-3 font-serif text-4xl font-bold">Operations control</h1><p class="mt-2 text-[#607a72]">Inventory, customer orders, purchasing, reporting, and business settings.</p></div>
        <div class="flex gap-3"><a href="{{ route('admin.users.index') }}" class="rounded-full bg-white/70 px-4 py-2 text-sm font-semibold">Accounts</a><form method="POST" action="{{ route('logout') }}">@csrf<button class="px-4 py-2 text-sm font-semibold underline">Sign out</button></form></div>
    </header>
    @if (session('status'))<p class="mt-6 rounded-2xl bg-[#d7f0df] px-4 py-3 text-sm text-[#187849]">{{ session('status') }}</p>@endif
    @if ($errors->any())<p class="mt-6 rounded-2xl bg-[#f5dcd7] px-4 py-3 text-sm text-[#b84331]">{{ $errors->first() }}</p>@endif

    <div class="mt-8 grid gap-6 xl:grid-cols-2">
        <section class="rounded-[28px] bg-[#edf7f5]/90 p-5 shadow-lg sm:p-7">
            <h2 class="font-serif text-2xl font-bold">Add flower stock</h2>
            <form method="POST" action="{{ route('admin.inventory.store') }}" class="mt-5 grid gap-3 sm:grid-cols-2">@csrf
                <input name="flower_type" placeholder="Flower type" required class="rounded-xl border-0 p-3"><input name="quantity" type="number" min="0" placeholder="Quantity" required class="rounded-xl border-0 p-3">
                <input name="unit_price" type="number" min="0" step="0.01" placeholder="Unit price" required class="rounded-xl border-0 p-3"><input name="date_received" type="date" required class="rounded-xl border-0 p-3">
                <input name="shelf_life_days" type="number" min="1" value="7" placeholder="Shelf life days" required class="rounded-xl border-0 p-3"><input name="low_stock_threshold" type="number" min="0" value="5" placeholder="Low stock threshold" required class="rounded-xl border-0 p-3">
                <button class="rounded-xl bg-[#e3953d] px-4 py-3 font-semibold text-white sm:col-span-2">Add stock item</button>
            </form>
        </section>
        <section class="rounded-[28px] bg-[#edf7f5]/90 p-5 shadow-lg sm:p-7">
            <h2 class="font-serif text-2xl font-bold">Send purchase order</h2>
            <form method="POST" action="{{ route('admin.purchase-orders.store') }}" class="mt-5 grid gap-3 sm:grid-cols-2">@csrf
                <select name="supplier_id" class="rounded-xl border-0 p-3"><option value="">Supplier name</option>@foreach ($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select><input name="supplier_name" placeholder="Supplier / company" required class="rounded-xl border-0 p-3">
                <input name="flower_type" placeholder="Flower type" required class="rounded-xl border-0 p-3"><input name="quantity" type="number" min="1" placeholder="Quantity" required class="rounded-xl border-0 p-3"><input name="requested_date" type="date" required class="rounded-xl border-0 p-3 sm:col-span-2">
                <button class="rounded-xl bg-[#285443] px-4 py-3 font-semibold text-white sm:col-span-2">Send purchase order</button>
            </form>
        </section>
    </div>

    <section class="mt-6 rounded-[28px] bg-[#edf7f5]/90 p-5 shadow-lg sm:p-7"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-serif text-2xl font-bold">Live inventory</h2><p class="mt-1 text-sm text-[#607a72]">Low stock and approaching spoilage are highlighted.</p></div></div>
        <div class="mt-5 overflow-x-auto"><table class="w-full min-w-[1050px] text-left text-sm"><thead class="border-b border-[#d4e4e0] text-xs uppercase text-[#607a72]"><tr><th class="pb-3">Flower</th><th class="pb-3">Quantity</th><th class="pb-3">Received</th><th class="pb-3">Shelf life</th><th class="pb-3">Actions</th></tr></thead><tbody class="divide-y divide-[#dce9e6]">@foreach ($inventory as $item) @php($spoilageDate = $item->date_received->copy()->addDays($item->shelf_life_days))<tr><td class="py-4 font-semibold">{{ $item->flower_type }} @if ($spoilageDate->lte(now()->addDays((int) ($settings['spoilage_alert_days'] ?? 2))))<span class="ml-2 rounded-full bg-[#f5dcd7] px-2 py-1 text-xs text-[#b84331]">Spoilage alert</span>@endif</td><td class="py-4 {{ $item->quantity <= $item->low_stock_threshold ? 'font-bold text-[#b84331]' : '' }}">{{ $item->quantity }}{{ $item->quantity <= $item->low_stock_threshold ? ' · low stock' : '' }}</td><td class="py-4">{{ $item->date_received->format('d M Y') }}</td><td class="py-4">{{ $item->shelf_life_days }} days <span class="block text-xs text-[#607a72]">{{ $spoilageDate->format('d M Y') }}</span></td><td class="py-4"><div class="flex flex-wrap gap-2"><form method="POST" action="{{ route('admin.inventory.adjust', $item) }}" class="flex gap-2">@csrf<input name="quantity_change" type="number" placeholder="+/-" required class="w-20 rounded-lg border-0 p-2"><input name="reason" placeholder="Reason" required class="w-36 rounded-lg border-0 p-2"><button class="font-semibold underline">Adjust</button></form><form method="POST" action="{{ route('admin.inventory.destroy', $item) }}">@csrf @method('DELETE')<button class="font-semibold text-[#b84331] underline">Delete</button></form></div><details class="mt-2"><summary class="cursor-pointer text-xs font-semibold underline">Edit</summary><form method="POST" action="{{ route('admin.inventory.update', $item) }}" class="mt-2 flex flex-wrap gap-2">@csrf @method('PUT')<input name="flower_type" value="{{ $item->flower_type }}" required class="w-28 rounded-lg border-0 p-2"><input name="quantity" type="number" min="0" value="{{ $item->quantity }}" required class="w-20 rounded-lg border-0 p-2"><input name="unit_price" type="number" min="0" step="0.01" value="{{ $item->unit_price }}" required class="w-24 rounded-lg border-0 p-2"><input name="date_received" type="date" value="{{ $item->date_received->format('Y-m-d') }}" required class="rounded-lg border-0 p-2"><input name="shelf_life_days" type="number" min="1" value="{{ $item->shelf_life_days }}" required class="w-20 rounded-lg border-0 p-2"><input name="low_stock_threshold" type="number" min="0" value="{{ $item->low_stock_threshold }}" required class="w-20 rounded-lg border-0 p-2"><button class="font-semibold underline">Save</button></form></details></td></tr>@endforeach</tbody></table></div>
    </section>

    <section class="mt-6 rounded-[28px] bg-[#edf7f5]/90 p-5 shadow-lg sm:p-7"><div class="flex flex-wrap items-end justify-between gap-3"><div><h2 class="font-serif text-2xl font-bold">Customer orders</h2><p class="mt-1 text-sm text-[#607a72]">Filter by collection date, status, or customer.</p></div><form class="flex flex-wrap gap-2"><input name="customer" value="{{ request('customer') }}" placeholder="Customer" class="rounded-lg border-0 p-2"><input name="date" value="{{ request('date') }}" type="date" class="rounded-lg border-0 p-2"><select name="status" class="rounded-lg border-0 p-2"><option value="">All statuses</option>@foreach (['pending','ready','completed','cancelled'] as $status)<option @selected(request('status') === $status)>{{ $status }}</option>@endforeach</select><button class="rounded-lg bg-[#285443] px-3 py-2 text-white">Filter</button></form></div><div class="mt-5 space-y-3">@forelse ($orders as $order)<div class="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-white/60 p-4"><div><p class="font-semibold">#{{ $order->id }} · {{ $order->customer_name }}</p><p class="text-sm text-[#607a72]">{{ $order->customer_email }} · Collection {{ $order->collection_date->format('d M Y') }} · {{ $order->items->map(fn ($item) => $item->quantity.' '.$item->flower_type)->join(', ') }}</p></div><form method="POST" action="{{ route('admin.orders.status', $order) }}">@csrf @method('PATCH')<select name="status" onchange="this.form.submit()" class="rounded-lg border-0 p-2"><option value="pending" @selected($order->status === 'pending')>Pending</option><option value="ready" @selected($order->status === 'ready')>Ready</option><option value="completed" @selected($order->status === 'completed')>Completed</option><option value="cancelled" @selected($order->status === 'cancelled')>Cancelled</option></select></form></div>@empty<p class="text-sm text-[#607a72]">No orders match the current filters.</p>@endforelse</div></section>

    <div class="mt-6 grid gap-6 xl:grid-cols-2"><section class="rounded-[28px] bg-[#edf7f5]/90 p-5 shadow-lg sm:p-7"><h2 class="font-serif text-2xl font-bold">Purchase orders</h2><div class="mt-4 space-y-3">@foreach ($purchaseOrders as $purchaseOrder)<div class="flex items-center justify-between gap-3 rounded-2xl bg-white/60 p-4"><div><p class="font-semibold">{{ $purchaseOrder->supplier_name }}</p><p class="text-sm text-[#607a72]">{{ $purchaseOrder->items->map(fn ($item) => $item->quantity.' '.$item->flower_type)->join(', ') }} · by {{ $purchaseOrder->creator->name }}</p></div><form method="POST" action="{{ route('admin.purchase-orders.status', $purchaseOrder) }}">@csrf @method('PATCH')<select name="status" onchange="this.form.submit()" class="rounded-lg border-0 p-2"><option value="sent" @selected($purchaseOrder->status === 'sent')>Sent</option><option value="fulfilled" @selected($purchaseOrder->status === 'fulfilled')>Fulfilled</option></select></form></div>@endforeach</div></section><section class="rounded-[28px] bg-[#edf7f5]/90 p-5 shadow-lg sm:p-7"><div class="flex items-center justify-between"><h2 class="font-serif text-2xl font-bold">Sales report</h2><a href="{{ route('admin.reports.export', request()->query()) }}" class="text-sm font-semibold underline">Export CSV</a></div><form class="mt-4 flex gap-2"><input name="from" value="{{ request('from') }}" type="date" class="rounded-lg border-0 p-2"><input name="to" value="{{ request('to') }}" type="date" class="rounded-lg border-0 p-2"><button class="rounded-lg bg-[#285443] px-3 py-2 text-white">Run report</button></form><table class="mt-5 w-full text-left text-sm"><tbody>@foreach ($report as $row)<tr class="border-b border-[#dce9e6]"><td class="py-2">{{ $row->flower_type }}</td><td class="py-2 text-right font-semibold">{{ $row->quantity }}</td></tr>@endforeach</tbody></table></section></div>

    <section class="mt-6 rounded-[28px] bg-[#edf7f5]/90 p-5 shadow-lg sm:p-7"><h2 class="font-serif text-2xl font-bold">Business settings</h2><form method="POST" action="{{ route('admin.settings.update') }}" class="mt-4 grid gap-3 sm:grid-cols-3">@csrf @method('PUT')<input name="business_name" value="{{ $settings['business_name'] ?? 'BloomKeeper' }}" placeholder="Business name" required class="rounded-xl border-0 p-3"><input name="business_contact" value="{{ $settings['business_contact'] ?? '' }}" placeholder="Contact info" class="rounded-xl border-0 p-3"><input name="spoilage_alert_days" type="number" min="0" value="{{ $settings['spoilage_alert_days'] ?? 2 }}" placeholder="Alert days before spoilage" required class="rounded-xl border-0 p-3"><button class="rounded-xl bg-[#e3953d] px-4 py-3 font-semibold text-white sm:col-span-3">Save settings</button></form></section>
</main>
</div>
</body></html>
